export const PLAY_SOUND = "PLAY_SOUND";
export const PAUSE_SOUND = "PAUSE_SOUND";
export const ADJUST_FOCUS = "ADJUST_FOCUS";

export const RESET_CONTROLS = "RESET_CONTROLS";

export const SET_SEEK = "SET_SEEK";

export const REQUEST_ADD_COMMENT = "REQUEST_ADD_COMMENT";
export const RECEIVE_ADD_COMMENT = "RECEIVE_ADD_COMMENT";
export const FAILURE_ADD_COMMENT = "FAILURE_ADD_COMMENT";