export const FETCH_SOUNDS = 'FETCH_SOUNDS';
export const FETCH_SOUNDS_SUCCESS = 'FETCH_SOUNDS_SUCCESS';
export const FETCH_SOUNDS_FAILURE = 'FETCH_SOUNDS_FAILURE';
export const RESET_SOUNDS = 'RESET_SOUNDS';

export const FETCH_SOUND = 'FETCH_SOUND';
export const FETCH_SOUND_SUCCESS = 'FETCH_SOUND_SUCCESS';
export const FETCH_SOUND_FAILURE = 'FETCH_SOUND_FAILURE';
export const RESET_ACTIVE_SOUND = 'RESET_ACTIVE_SOUND';

export const CREATE_SOUND = 'CREATE_SOUND';
export const CREATE_SOUND_SUCCESS = 'CREATE_SOUND_SUCCESS';
export const CREATE_SOUND_FAILURE = 'CREATE_SOUND_FAILURE';

