export const REQUEST_SOUND = 'REQUEST_SOUND';
export const RECEIVE_SOUND = 'RECEIVE_SOUND';
export const FAILURE_SOUND = 'FAILURE_SOUND';

export const REQUEST_CREATE_SOUND = 'CREATE_SOUND';
export const CREATE_SOUND_SUCCESS = 'CREATE_SOUND_SUCCESS';
export const CREATE_SOUND_FAILURE = 'CREATE_SOUND_FAILURE';






//currently unused
export const FETCH_SOUNDS_FAILURE = 'FETCH_SOUNDS_FAILURE';
export const RESET_SOUNDS = 'RESET_SOUNDS';

export const FETCH_SOUND = 'FETCH_SOUND';
export const FETCH_SOUND_SUCCESS = 'FETCH_SOUND_SUCCESS';
export const FETCH_SOUND_FAILURE = 'FETCH_SOUND_FAILURE';
export const RESET_ACTIVE_SOUND = 'RESET_ACTIVE_SOUND';


export const UPLOAD_ENDPOINT = '';
