export const REQUEST_SOUND = 'REQUEST_SOUND';
export const RECEIVE_SOUND = 'RECEIVE_SOUND';
export const FAILURE_SOUND = 'FAILURE_SOUND';

export const REQUEST_CREATE_SOUND = 'CREATE_SOUND';
export const RECEIVE_CREATE_SOUND = 'RECEIVE_CREATE_SOUND';
export const FAILURE_CREATE_SOUND = 'FAILURE_CREATE_SOUND';

export const REQUEST_SOUNDS = 'REQUEST_SOUNDS';
export const RECEIVE_SOUNDS = 'RECEIVE_SOUNDS';
export const FAILURE_SOUNDS = 'FAILURE_SOUNDS';

export const CLEAR_LOADED_SOUNDS = 'CLEAR_LOADED_SOUNDS';

export const REQUEST_ADD_COMMENT = "REQUEST_ADD_COMMENT";
export const RECEIVE_ADD_COMMENT = "RECEIVE_ADD_COMMENT";
export const FAILURE_ADD_COMMENT = "FAILURE_ADD_COMMENT";

export const REQUEST_GET_COMMENTS = "REQUEST_GET_COMMENTS";
export const RECEIVE_GET_COMMENTS = "RECEIVE_GET_COMMENTS";
export const FAILURE_GET_COMMENTS = "FAILURE_GET_COMMENTS";


//currently unused
export const FETCH_SOUNDS_FAILURE = 'FETCH_SOUNDS_FAILURE';
export const RESET_SOUNDS = 'RESET_SOUNDS';

export const FETCH_SOUND = 'FETCH_SOUND';
export const FETCH_SOUND_SUCCESS = 'FETCH_SOUND_SUCCESS';
export const FETCH_SOUND_FAILURE = 'FETCH_SOUND_FAILURE';
export const RESET_ACTIVE_SOUND = 'RESET_ACTIVE_SOUND';


export const UPLOAD_ENDPOINT = '';
